typography_spectrum: 0.6932068485766649
color:
  brandStrength: 0.5890206918120384
  lightness: 0.21725934487767518
  saturation: 0.26318711997009814
  rhythmicContrast: 0.2599716398399323
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.25682438677176833
author:
  name: ''
  email: alaw2k@yahoo.com
  url: 'http://Creotivity.com'
name: Creotivity
navigation:
  - name: Captures
    id: 53dc190a-59a7-4493-8823-b09d14116750
    type: content
  - name: About me
    id: 8a13ce8f-25b7-4449-b01c-0f89f0de4f7b
    type: content
  - name: Motion
    id: dc37d9f7-358c-4189-9a08-fc0f26ee11a1
    type: content
title: Creotivity
description: be creative
