typography_spectrum: 0.6932068485766649
color:
  brandStrength: 0.5890206918120384
  lightness: 0.21725934487767518
  saturation: 0.26318711997009814
  rhythmicContrast: 0.2599716398399323
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.25682438677176833
author:
  name: Alan Law
  email: alaw2k@yahoo.com
  url: 'http://Creotivity.com'
name: Creotivity
navigation:
  - name: Captures
    id: 9d815719-7315-44fc-9506-976d84036a18
    type: content
  - name: About me
    id: 8a13ce8f-25b7-4449-b01c-0f89f0de4f7b
    type: content
title: Creotivity
description: be creative
