layout_spectrum: 0.5627555199898779
typography_spectrum: 0.535956708015874
color:
  brandStrength: 0.3280396868940443
  lightness: 0.5905095359776169
  saturation: 0.8030510391108692
  rhythmicContrast: 0.9655500252265483
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
name: Creotivity
