typography_spectrum: 0.535956708015874
color:
  brandStrength: 0.3280396868940443
  lightness: 0.5905095359776169
  saturation: 0.8030510391108692
  rhythmicContrast: 0.9655500252265483
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.5627555199898779
name: Creotivity
navigation:
  - name: About me
    id: 8a13ce8f-25b7-4449-b01c-0f89f0de4f7b
    type: content
  - name: Captures
    id: 9d815719-7315-44fc-9506-976d84036a18
    type: content
title: Life is simple
description: be creative
